### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by icinsight** [0xProject/0x-launch-kit#7]
Based on my discussions in Discord I realized that there is a missing step 2. in instructions:

1. Install Pre-requirements:
Node.js > v8.x
Yarn > v1.x
Docker
npx

2. Clone the repo:
git clone https://github.com/0xProject/0x-launch-kit.git

3. Run the wizard
npx @0x/launch-kit-wizard && docker-compose up

Also: Please be prepared to wait up to five (5) minutes to get all the background services properly running before trying to check your http://[host]:3001

**Comment by tomhschmidt** [comment]
Hey @icinsight -- you actually don't need to clone because npx will download the package from npm and then it run it. Installing node should also install npm / npx.

We're working on the load time with https://github.com/0xProject/0x-launch-kit-frontend/pull/499 , which will show a loading screen while docker is booting

**Comment by icinsight** [comment]
All right, I didn't realize that. Someone got his installation working only after git clone. For some reason?
